apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /policies
    apps.open-cluster-management.io/reconcile-rate: high
  name: deploy-integration-subscription
  namespace: acm-channels
spec:
  channel: acm-channels/deploy-integration-channel
  placement:
    local: true
