apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-integrations

placementRef:
  name: rule-integrations
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: policy-camel-k-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io

