apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rule-integrations

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: integrations, operator: In, values: ["yes"]}
