apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: integrations-operators
  annotations:
    policy.open-cluster-management.io/standards: Outils d'intégrations
    policy.open-cluster-management.io/categories: Operators
    policy.open-cluster-management.io/controls: Standards applicatif
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:

  - objectDefinition:
      # Install Camel-K operator
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: cp-camel-k-operator
      spec:
        remediationAction: inform
        severity: high
        object-templates:

          - complianceType: musthave
            objectDefinition:

              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                labels:
                  operators.coreos.com/camel-k.openshift-operators: ""
                name: camel-k
                namespace: openshift-operators
              spec:
                channel: stable-1.5
                installPlanApproval: Automatic
                name: camel-k
                source: community-operators
                sourceNamespace: openshift-marketplace
                startingCSV: camel-k-operator.v1.5.0