apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: integrations-projects
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/categories: Securité infrastructure
    policy.open-cluster-management.io/controls: Configurations
    policy.open-cluster-management.io/standards: Configurations
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: integrations-projects
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:

                apiVersion: project.openshift.io/v1
                kind: Project
                metadata:
                  name: integrations-dev

            - complianceType: musthave
              objectDefinition:

                apiVersion: project.openshift.io/v1
                kind: Project
                metadata:
                  name: integrations-preprod

            - complianceType: musthave
              objectDefinition:

                apiVersion: project.openshift.io/v1
                kind: Project
                metadata:
                  name: integrations-prod